# 워크플로우 이름
name: Run Lint and Build

# 워크플로우 실행 조건
on:
  pull_request:
    branches:
      - main
      - develop

# 워크플로우 실행에 필요한 권한
permissions:
  contents: read
  pull-requests: write

# 실행할 작업(Job)
jobs:
  # 작업 ID
  build-and-test:
    # 작업 이름 (GitHub Actions UI에 표시됨)
    name: Build and Test
    # 작업을 실행할 가상 머신 환경
    runs-on: ubuntu-latest

    # 작업의 단계(Step)들
    steps:
      # 1. 리포지토리 코드를 가상 머신으로 가져오기
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.js 22 버전 설치 및 pnpm 캐시 설정
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      # 3. 의존성 설치 (pnpm-lock.yaml 기반으로 정확하게 설치)
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4. Lint 검사 실행
      - name: Run Lint Check
        run: pnpm run lint

      # 5. 빌드 실행
      - name: Run Build
        run: pnpm run build
